services:
  db:
    image: postgres:15-alpine
    container_name: immersio-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-geheim}
      POSTGRES_DB: ${DB_NAME:-immersio_db}
      PGDATA: /var/data/pgdata
    volumes:
      - postgres_data:/var/data/pgdata
    ports:
      - "5435:5432"
    networks:
      - immersio-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-immersio_db}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: immersio-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - ./backend/.env
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-geheim}@db:5432/${DB_NAME:-immersio_db}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - immersio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: immersio-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - immersio-network

volumes:
  postgres_data:

networks:
  immersio-network:
    driver: bridge