graph TB
    subgraph Client["Client layer"]
        HTTP["HTTP client (curl / Postman)"]
        Swagger["FastAPI Swagger UI (/docs)"]
        Frontend["Dengwa AI Frontend"]
        HTTP ~~~ Swagger ~~~ Frontend
    end

    subgraph Backend["Backend layer (FastAPI)"]
        Controller["Main — main.py"]
        Schemas["Schemas — schemas.py"]
        Models["Models — models.py"]
        Database["database.py"]

        subgraph Routers["Router layer (routers/)"]
            direction LR
            SystemRouter["system.py"]
            UserRouter["users.py"]
            LanguageRouter["languages.py"]
            MediaRouter["media.py"]
            VocabRouter["vocabularies.py"]
            ReviewRouter["reviews.py"]
            ChatRouter["chats.py"]
            SystemRouter ~~~ UserRouter
            UserRouter  ~~~ LanguageRouter
            LanguageRouter ~~~ MediaRouter
            MediaRouter ~~~ VocabRouter
            VocabRouter ~~~ ReviewRouter
            ReviewRouter ~~~ ChatRouter
        end

        subgraph Services["Service layer (services/)"]
            direction LR
            System["system.py"]
            Users["users.py"]
            Language["language_service.py"]
            Media["media_service.py"]
            Vocab["vocabulary_service.py"]
            Review["review_service.py"]
            Chat["chat_service.py"]
            System ~~~ Users
            Users ~~~ Language
            Language ~~~ Media
            Media ~~~ Vocab
            Vocab ~~~ Review
            Review ~~~ Chat
        end
        subgraph LLMServices["LLM Service layer (llm/)"]
            LLM["llm_service.py"]
            Prompts["prompts.py"]
        end

        Controller --> Routers
        Routers <-->|validation| Schemas
        Services <-->|Data| Database
        Routers --> Services
        Services <--> LLMServices
    end

    subgraph DB["Database layer"]
        Postgres[("PostgreSQL")]
    end

    subgraph AI["External AI APIs"]
        Groq["Groq"]
        Gemini["Google Gemini"]
        OpenAI["OpenAI"]
        Ollama["Ollama"]
        Groq ~~~ Gemini ~~~ OpenAI ~~~ Ollama
    end

    Client -->|HTTP / JSON| Controller
    LLM -->|HTTPS / API Key| AI
    Schemas <--> Models
    Models <--> Database
    Database <-->|SQLAlchemy| Postgres

