erDiagram
    chat_histories }o--|| chats: references
    chats }o--|| media: references
    media_chunks }o--|| media: references
    language_learning }o--|| users: references
    language_learning ||--o{ media: references
    learning_progress }o--|| media: references
    media_vocabularies }o--|| media: references
    vocabularies ||--o{ media_vocabularies: references
    vocabularies }o--|| language_learning: references
    chats }o--|| users: references

    users {
        UUID id
        TEXT username
        TEXT hashed_password
        TEXT native_language
    }

    media {
        UUID id
        TEXT title
        TEXT content_type
        TEXT file_path
        TEXT extracted_content
        UUID learning_id
    }
    media_chunks {
        UUID id
        UUID media_id
        TEXT content
        VECTOR embedding
    }

    vocabularies {
        UUID id
        UUID learning_id
        TEXT word
        TEXT translation
        TEXT context_sentence
        TEXT language
        TIMESTAMP created_at
        TIMESTAMP due
        INTEGER interval_days
        FLOAT ease_factor
        INTEGER repetitions
        INTEGER lapses
        FLOAT llm_mastery_score
        TEXT llm_notes
        TIMESTAMP last_interaction
    }

    chats {
        UUID id
        UUID media_id
        UUID user_id
    }

    chat_histories {
        UUID id
        UUID chat_id
        UUID parent_id
        TEXT message
        TEXT role
        TEXT provider
        TEXT model
        TEXT embedding_model
        TIMESTAMP timestamp
    }

    language_learning {
        UUID id
        UUID user_id
        TEXT learning_language
        TEXT proficiency_level
        TEXT user_motivation
    }

    learning_progress {
        UUID id
        UUID media_id
        TEXT proficiency_level
        TEXT comment
    }

    media_vocabularies {
        UUID id
        UUID media_id
        UUID vocabulary_id
    }